<?php

namespace AppBundle\Repository;

/**
 * TopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopRepository extends \Doctrine\ORM\EntityRepository
{
}
