# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.text:
        class: 'Twig_Extensions_Extension_Text'
        tags:
            - { name: twig.extension }

    AppBundle\Manager\PlayerManager:
        class: 'AppBundle\Manager\PlayerManager'
        autowire: true

    AppBundle\Manager\SchemaManager:
        class: 'AppBundle\Manager\SchemaManager'
        autowire: true

    AppBundle\Manager\GameManager:
        class: 'AppBundle\Manager\GameManager'
        autowire: true
